spring.application.name=neetcounsel
spring.profiles.active=development
spring.data.mongodb.uri=mongodb+srv://itsadityachand:uIWkGRI0JdD8PWtS@counselling.fnvna.mongodb.net/counselling

spring.security.oauth2.client.registration.google.client-id=397760532844-bsk9eo3982qeg7us53gd4oanr9g88oj0.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=email,profile

razorpay.key_id=rzp_test_pxUPmrfzQX2iIG
razorpay.key_secret=5YMXAOnbm1THbMEjKjKXxXGu

jwt.secret=y2jw94j39g394gj430wjwe2iyefgw439rufwjfg9w3ht7bfd7ue3rgifodkieu47rfeio34r76f56yui
jwt.expiration.ms=86400000 # 24 hours

server.servlet.session.tracking-modes=URL
server.servlet.session.cookie.http-only=false

