pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'tejasvi18/neetcounsel'
        DOCKER_TAG = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build JAR') {
            steps {
                dir('neetcounsel') {
                sh 'chmod +x mvnw'
            sh './mvnw clean package -DskipTests'
        }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    try {
                    dir('neetcounsel'){
                dockerImage = docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}")
                }
            } catch (e) {
                echo "Failed to build Docker image: ${e.getMessage()}"
                error("Stopping pipeline due to Docker build failure.")
            }
                }
            }
        }

        stage('Login to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    dockerImage.push()
                }
            }
        }
    }
}
